### ISSUE TITLE
Not working in Firefox 60.3.0esr (32-bit)

### ISSUE THREAD

**Issue by CruxRU** [elliotwaite/thumbnail-rating-bar-for-youtube#10]
After installation of this add-on the red progress bar of all videos on Youtube moved to the top of thumbnails, but nothing appeared instead of, hovering mouse above the bottoms of thumbnails doesn't help - nothing changes. I tried changing this add-on's settings and disabled all other youtube related add-ons - nothing helped.

**Comment by elliotwaite** [comment]
Hey CruxRU, thanks for reporting this issue. I currently don't have a way to test this add-on with the 60.3.0esr (32-bit) version of Firefox. I have Firefox 63.0.1 (64-bit) on my computer and I am able to see the rating bars on the bottom of the thumbnails. If you look at the console output window (Cmd+Shift+J on Mac, or Ctrl+Shift+J on Windows), do you see any error messages when loading a YouTube page with thumbnails that look like they may be related to the add-on?

**Comment by CruxRU** [comment]
Not sure actually. I opened youtube.com with your add-on disabled:

Error: ID already exists: detect-forms  ext-menus.js
Error: ID already exists: generate-password  ext-menus.js
Error: WebExtension context not found!  ExtensionParent.jsm:861:13
<source> element has no “src” attribute. Media resource load failed.  www.youtube.com
All candidate resources failed to load. Media load paused.  www.youtube.com
Logging system initialised at Sat Nov 10 2018 13:51:10 GMT+0300 (Russia TZ 2 Standard Time)  common.js:206:17
Logging system initialised at Sat Nov 10 2018 13:51:10 GMT+0300 (Russia TZ 2 Standard Time)  common.js:206:17
Logging system initialised at Sat Nov 10 2018 13:51:11 GMT+0300 (Russia TZ 2 Standard Time)  common.js:206:17
HTTP POST: ./?_task=mail&_action=refresh  app.min.js:62:200
this.set_unread_count("INBOX",3,true,"");
  app.min.js:62:200
Logging system initialised at Sat Nov 10 2018 13:51:13 GMT+0300 (Russia TZ 2 Standard Time)  common.js:206:17
Navigation error
      tabId: 48
      url: about:blank
      error: Error code 2152398850  utils.js:188:7
cannot inject content script /js/bootstrap.js into url about:blank on tab 48 and frame 6442451167  utils.js:188:7
cannot inject content script /js/contentscripts/fingercounting.js into url about:blank on tab 48 and frame 6442451167  utils.js:188:7
cannot inject content script /js/initialize_contentscripts.js into url about:blank on tab 48 and frame 6442451167  utils.js:188:7
cannot inject content script /js/bootstrap.js into url about:blank on tab 48 and frame 6442451169  utils.js:188:7
cannot inject content script /js/contentscripts/fingercounting.js into url about:blank on tab 48 and frame 6442451169  utils.js:188:7
cannot inject content script /js/initialize_contentscripts.js into url about:blank on tab 48 and frame 6442451169  utils.js:188:7
Error: ID already exists: detect-forms  ext-menus.js
Error: ID already exists: generate-password  ext-menus.js
Error: ID already exists: matchedLogin-0  ext-menus.js



Then I enabled the add-on and reloaded youtube.com (viewer's red bar moved to the top of thumbnails and still nothing on the bottoms):

1541847222115	addons.webextension.{75ae8986-4c3e-4a52-a256-f8496f6a1fa8}	WARN	Please specify whether you want browser_style or not in your browser_action options.
Error: WebExtension context not found!  ExtensionParent.jsm:861:13
<source> element has no “src” attribute. Media resource load failed.  www.youtube.com
All candidate resources failed to load. Media load paused.  www.youtube.com
Error: WebExtension context not found!  ExtensionParent.jsm:861:13
Logging system initialised at Sat Nov 10 2018 13:53:54 GMT+0300 (Russia TZ 2 Standard Time)  common.js:206:17
Logging system initialised at Sat Nov 10 2018 13:53:55 GMT+0300 (Russia TZ 2 Standard Time)  common.js:206:17
SecurityError: Permission denied to access property "URL" on cross-origin object  initialize_contentscripts.js:28
Logging system initialised at Sat Nov 10 2018 13:53:55 GMT+0300 (Russia TZ 2 Standard Time)  common.js:206:17
Logging system initialised at Sat Nov 10 2018 13:53:57 GMT+0300 (Russia TZ 2 Standard Time)  common.js:206:17
Navigation error
      tabId: 48
      url: about:blank
      error: Error code 2152398850  utils.js:188:7
Navigation error
      tabId: 48
      url: about:blank
      error: Error code 2152398850  utils.js:188:7
cannot inject content script /js/bootstrap.js into url about:blank on tab 48 and frame 6442451180  utils.js:188:7
cannot inject content script /js/contentscripts/fingercounting.js into url about:blank on tab 48 and frame 6442451180  utils.js:188:7
cannot inject content script /js/initialize_contentscripts.js into url about:blank on tab 48 and frame 6442451180  utils.js:188:7
cannot inject content script /js/bootstrap.js into url about:blank on tab 48 and frame 6442451182  utils.js:188:7
cannot inject content script /js/contentscripts/fingercounting.js into url about:blank on tab 48 and frame 6442451182  utils.js:188:7
cannot inject content script /js/initialize_contentscripts.js into url about:blank on tab 48 and frame 6442451182  utils.js:188:7

Hope it helps to find the reason.

**Comment by elliotwaite** [comment]
Thanks for posting the console log. I don't notice anything in there related to the thumbnail rating bar extension. I'm not sure how to help further with trying to get this extension to work with your system. Here are some similar extension that you could try to see if any of these work better for you:

https://chrome.google.com/webstore/detail/ratings-preview-for-youtu/piaphheklodiededmbmgfcfbcagncgka/

https://chrome.google.com/webstore/detail/ratings-preview-for-youtu/cgbhdenfmgbagncdmgbholejjpmmiank?hl=en

**Comment by CruxRU** [comment]
Thank you, somehow I didn't find 'Ratings Preview for YouTube' before, it works in my firefox.
Btw, I tried one more thing with your add-on, while adjusting thickness it leads to movement up or down the time length of videos on thumbnails.
