### ISSUE TITLE
Extension file unchanged after update.

### ISSUE THREAD

**Issue by mihirkumar** [elliotwaite/thumbnail-rating-bar-for-youtube#13]
The download link for the extension: https://raw.githubusercontent.com/elliotwaite/thumbnail-rating-bar-for-youtube/master/zipped/thumbnail-rating-bar-for-youtube.zip still points to the zipped version of the old version of the extension. Please zip the latest version and set that as the file where this link points. A tiny housekeeping issue! :)

**Comment by elliotwaite** [comment]
Thanks! Fixed it.
