### ISSUE TITLE
Error in manifest file

### ISSUE THREAD

**Issue by Gitoffthelawn** [elliotwaite/thumbnail-rating-bar-for-youtube#14]
If you go to `about:debugging` in Firefox, this extension causes the following warning/error:

>  Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.

Does this warrant an update?

**Comment by elliotwaite** [comment]
Fixed (in the latest release, version 0.0.41). I made the background script persistent since nonpersistent background scripts aren't supported in Firefox yet.

Thanks for reporting this!

**Comment by Gitoffthelawn** [comment]
You're welcome, and thank ***you!***

**Comment by Gitoffthelawn** [comment]
BTW, would it be a good idea for you to set up a to-do item to make it nonpersistent when FF supports it in the future?

**Comment by elliotwaite** [comment]
Good idea. I've added a TODO comment in the code (https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/blob/master/tools/build_package.py#L30). Is that what you were suggesting, or is there another way to create to-do items on GitHub that I don't know about?

**Comment by Gitoffthelawn** [comment]
That's exactly what I was thinking, along with a GitHub issue report with one or two tags, such as `future` and `firefox`.  That way it can stay open, but you (and others) can see the tags.

**Comment by elliotwaite** [comment]
Gotcha, good idea. I've opened a new issue about it. Thanks for the tips.
