### ISSUE TITLE
Previews have stopped working

### ISSUE THREAD

**Issue by SpamCam** [elliotwaite/thumbnail-rating-bar-for-youtube#18]
The like bar no longer displays under the thumbnails.

**Comment by SpamCam** [comment]
Wait. I just fixed it by following this guide: https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/issues/17#issuecomment-557923841

**Comment by elliotwaite** [comment]
Nice. Glad that fixed it for you. I'm going to close this issue, but feel free to open another if you run into any other issues.
