### ISSUE TITLE
Settings menu refuses to open in Firefox

### ISSUE THREAD

**Issue by Hyde233** [elliotwaite/thumbnail-rating-bar-for-youtube#21]
For some reason, the settings menu refuses to open. It stays stuck on a blank white screen:
![d](https://user-images.githubusercontent.com/37200259/72690491-88c73d00-3ae2-11ea-8df2-e153f7916d6d.png)

I've tried uninstalling and reinstalling the extension, and I've restarted my computer a couple of times, but it still doesn't work. I also tried disabling every other extension to see if it'll do anything; it still won't work.

I decided to try installing the extension on an alternate profile, and it worked on that one. The menu just refuses to open on the main profile I want to use it on for some reason.

**Comment by elliotwaite** [comment]
Stange, I haven't heard of this issue occurring before. What browser version are you using?

**Comment by Hyde233** [comment]
> 
> 
> Stange, I haven't heard of this issue occurring before. What browser version are you using?

I'm currently using version 72.0.2 (64 bit).

On a side note, I also tried opening the plugin menu on another computer and I'm having the same issue. Both computers are connected with the same Firefox profile, so I think the issue might have something to do with my Firefox profile and/or browser settings.

**Comment by elliotwaite** [comment]
I was unable to reproduce the error using Firefox version 72.0.2 (64 bit) and Thumbnail Rating Bar for YouTube™ version 0.1.2.

Perhaps you can check if the extension is producing any informative error messages:
1. Navigate to "about:debugging#/runtime/this-firefox" .
2. Click the "Inspect" button next to the "Thumbnail Rating Bar for YouTube™" extension, which will open a new tab with a view of a console.
3. Then click the extension button in the toolbar to try to open the settings window.
4. Check if any error messages were printed to the console.

**Comment by Hyde233** [comment]
Three messages appeared:

> Could not map contract ID '@mozilla.org/sharepicker;1' to CID {1201d357-8417-4926-a694-e6408fbedcf8} because no implementation of the CID is registered.

>The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. (main.html)

>The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. (options-popup.html)

The first two messages already appeared before I tried opening the settings menu. The third one appeared after.

**Comment by elliotwaite** [comment]
Ok, I get that third one two, so I don't think it is the cause of the issue.

I'm not sure what else to try. If you somehow figure out a solution in the future through changing the account settings or something, I'd be interested to here what fixed it.

**Comment by Hyde233** [comment]
I figured out what the issue is. It wouldn't open because it was pinned to the overflow menu. After I unpinned it, it started working again.

**Comment by elliotwaite** [comment]
Got it. Good to know. Thanks for posting the fix.
