### ISSUE TITLE
suddenly stopped working

### ISSUE THREAD

**Issue by komaedalove** [elliotwaite/thumbnail-rating-bar-for-youtube#22]
google reworked their whole api setting up site and the instructions to get api key are outdated

**Comment by elliotwaite** [comment]
Thanks for reporting this. I just tried out the instructions and they still seemed to work for me. I updated the instructions slightly by changing some of the button text titles (which were slightly incorrect), but you may be referring to something else. What part of the instructions differed for you?

**Comment by komaedalove** [comment]
it works now thank you
