### ISSUE TITLE
[Feature Request] Change thickness of video rating bar

### ISSUE THREAD

**Issue by ItsPasi** [elliotwaite/thumbnail-rating-bar-for-youtube#23]
Hello, after the addon "Ratings Preview for YouTube" got blocked, I am using this as an alternative. It works flawless but it is missing one feature. The like/dislike bar on videos themself is still really thin and I find it harder that way to see the differences. If that would be possible to implement I would love you.

**Comment by elliotwaite** [comment]
I probably won't implement this feature, but you can accomplish this quite easily with the Stylebot Chrome extension:
https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha

You can change the style of elements on websites and they will keep that style even when you revisit it or view a different video. I made this screen recording demonstrating how you would use it to change the rating bar height on the video page:
https://youtu.be/fWaS55FfMeI

**Comment by pasi123567** [comment]
I don't use Chrome. I tried with Stylish but it won't stay after refresh

**Comment by elliotwaite** [comment]
Which browser do you use?

**Comment by ItsPasi** [comment]
Honestly doesn't fit with the functionality of this extension (just closing old issues rn)
