### ISSUE TITLE
Settings page is problematic

### ISSUE THREAD

**Issue by ak47wong** [elliotwaite/thumbnail-rating-bar-for-youtube#24]
Hi Elliot, a few months ago I had the problem that when I open the settings page, it was blank. I never figured out why or how to fix it, so I just ignored for a while.

Now I've tried again and the settings page isn't blank, but the API section is missing:

![options-popup](https://user-images.githubusercontent.com/42455773/82335352-8d6a1680-9a2c-11ea-9ee5-dd8a985039b3.png)

Any fix for this?

**Comment by elliotwaite** [comment]
Hmm. Was the API section visible in the past? Have you checked to make sure you have the latest version installed (version 0.1.2)? You could try uninstalling and reinstalling if you haven't tried that yet.

Someone had a similar problem when using Firefox and when the extension was pinned to the overflow menu (full details here: https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/issues/21), but I'm not sure if this is the same issue you are having.

**Comment by ak47wong** [comment]
Thanks Elliot. I had 0.0.41 installed but AMO didn't detect any updates for some reason. Uninstalling and reinstalling fixed it. You're awesome!

As for pinning the extension icon to the overflow menu, the popup window is too small, but the fields are there. It just needs to be scrolled around:
![image](https://user-images.githubusercontent.com/42455773/82513635-f2ba2680-9b56-11ea-8188-d43e20c09fa5.png)

**Comment by elliotwaite** [comment]
Good to hear.
