### ISSUE TITLE
plssss make it show % like 99.3% and color-coded, there's still no extensions that does this, there used to be, most important thing

### ISSUE THREAD

**Issue by SolveEverything** [elliotwaite/thumbnail-rating-bar-for-youtube#26]
^

**Comment by mihirkumar** [comment]
The heading should be a concise version of your request and put details in the description.

**Comment by elliotwaite** [comment]
I currently do not have time to implement this feature, but if someone is willing to create a PR for this, I would be open to reviewing it.

**Comment by SolveEverything** [comment]
dunno code, learning very slowly 

requested this a year ago btw whenever it can be achieved would be good

**Comment by elliotwaite** [comment]
Just found an extension that implements this feature. It adds the likes percentage below the thumbnail next to the release time, and it's color-coded! Looks pretty good to me.

<img width="1140" alt="Screen Shot 2020-06-12 at 5 11 12 PM" src="https://user-images.githubusercontent.com/1767836/84555060-c74ad780-accf-11ea-9622-f32dc468c022.png">

The extension is called vidIQ Vision for YouTube:
https://chrome.google.com/webstore/detail/vidiq-vision-for-youtube/pachckjkecffpdphbpmfolblodfkgbhl?hl=en

The extension offers a lot of extra features for YouTube creators, but if you want, you can turn off all the other features and only enable the "Like to Dislike Ratio" option.

Let me know if this works as an alternative for you.

**Comment by knoajp** [comment]
Wow, I'm curious about if this extension has plenty of API quota or some alternate solution.
(I browsed its code but it was minified)

**Comment by elliotwaite** [comment]
@knoajp, not sure, but vidIQ has been around for a long time, so I'm thinking they were able to work out a deal with YouTube to increase their quota.

**Comment by mihirkumar** [comment]
This does look like a cool feature.

**Comment by Chiramisu** [comment]
> The extension is called vidIQ Vision for YouTube:
> 
> The extension offers a lot of extra features for YouTube creators, but if you want, you can turn off all the other features and only enable the "Like to Dislike Ratio" option.

Cool. I did just that, and also used my Ad Blocker to block their annoying login box at the top of the recommended videos on every page. Blah! 😋

**Comment by makethingsbetter** [comment]
what in the web!...

how did you find this, do you remember

tested, this isnt helpful cos you cant change the color of various %

there was an extension a long time ago that had 3 tiers of color and you could choose the % threshold, was very simple but the student that made it deleted it

if someone could make this one day, that would be great, should be super simple for those that know code

**Comment by makethingsbetter** [comment]
for quota

there's no way... it does look like vidIQ  is a relatively not small company with 4m in funding but youtube is huge and it's unlikely they would give any special exceptions, maybe youtube has some kind of business option

or maybe vidiq has multiple accounts using the api  but that's technical stuff i'd know nothing about

**Comment by elliotwaite** [comment]
> how did you find this, do you remember

I've been using VidIQ for a long time just for their YouTube creator tools and they recently added this feature to show the like percentages.

> tested, this isnt helpful cos you cant change the color of various %
> 
> it's actually less helpful than the rating bar cos you cant change the color of various %
> 
> the whole reason why % is helpful is cos it's color-coded, that's what makes it useful helpful
> 
> there was an extension a long time ago that had 3 tiers of color and you could choose the % threshold, was very simple but the cs student that made it deleted it
> 
> if someone could make this one day, that would be great, should be super simple for those that know code

I'll leave this issue open in case someone wants to implement this feature.

**Comment by elliotwaite** [comment]
This feature has been added by @xethlyx: https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/pull/30. It's available in version 1.1.0.

There is now an option to "Add a color-coded rating percentage to each listing." If you have any feedback about this new feature (suggestions, bugs, etc.), leave a comment below.

I'm going to close this issue but I can re-open it if this feature needs further development.
