### ISSUE TITLE
Ratings bar on actual video-pages isn't coloured anymore

### ISSUE THREAD

**Issue by scharmach** [elliotwaite/thumbnail-rating-bar-for-youtube#32]
The bar on the video-pages was coloured at some point too, or wasn't it?

![grafik](https://user-images.githubusercontent.com/9080980/106524519-fa520d80-64e2-11eb-8104-f0b4b4175741.png)

https://www.youtube.com/watch?v=dQw4w9WgXcQ

Just noticed this now and I've also seen that there was a new update as of today (1.2.1). Did this have an effect on this issue or am I imaging things?

**Comment by elliotwaite** [comment]
Ah, thanks for pointing this out. It actually depends on which color theme for the rating bar you were using. If you were using the green/red theme, then yes, it is supposed to be colored there and I messed that up with the recent update. But I just released a fix for that, version 1.2.2.

However, if you were using the blue/gray theme, then that rating bar actually doesn't get colored by the extension and it just uses whatever YouTube sets it to by default (as in whatever color it would be if the extension was disabled). But maybe YouTube recently changed the default color of that rating bar, cause I remember at some point it used to be blue/gray, but I'm not sure how long ago that was. Also, to make sure this is how the extension also worked before the recent update, I installed an older version of the extension and it behaved the same way. I'm not sure what would be the best way to handle this for the plugin, but I think I like the current behavior where the blue/gray theme just uses the default colors for that rating bar. But if you think there should be an option to always use the colors set in the extension for this rating bar as well, I could and an option for that, something like "Also change the colors of the rating bar on the video page."

**Comment by scharmach** [comment]
Thanks for getting a fix out so quickly, it's working again now:

![grafik](https://user-images.githubusercontent.com/9080980/106575359-45e4d580-653c-11eb-9534-241922169e5a.png)

I'm always using the green/red-theme, so I never noticed that my screenshot above would in fact be the default behaviour if the blue/gray-theme is set:

![grafik](https://user-images.githubusercontent.com/9080980/106575509-762c7400-653c-11eb-80f1-b32f02460dcb.png)

I did a quick search and have also noticed that this bar was blue by default at some point, so YouTube seems indeed to have changed this.

I also think that an option like "Also change the colors of the rating bar on the video page." is a great idea. This would lead to more consistency around this feature too, because right now:

- Greed/red-theme = video-page bar is coloured and no option to change this if you don't like it other than switching themes

- Blue/grey-theme = the other way around, not coloured by default and can't be coloured right now

With an option this could be more streamlined:

- Not checked would mean the default grey bar regardless of theme

- Checked would mean either blue/grey- or green/red-colouring, depending on the theme

**Comment by elliotwaite** [comment]
I added a new option: "Use the rating bar colors for the rating bar on the video page." It's been added in version 1.3.0.

It defaults to false since that was the default behavior for the default blue/gray colors, so you'll have to set it to true to get back to the default behavior for the green/red colors.

Let me know if the update solves this issue.

**Comment by scharmach** [comment]
Once again, thanks for the quick implementation! I've let 1.3.0 install, did some testing and the new option works as expected for both themes, checked or not.

I will therefore close this issue with this comment.
