### ISSUE TITLE
Like/dislike percentage not visible on video page anymore

### ISSUE THREAD

**Issue by ictilkka** [elliotwaite/thumbnail-rating-bar-for-youtube#41]
Hovering over the like/dislike bar below video no longer shows like/dislike percentage, but only "likes / dislikes", which is Youtube's default behavior without the extension. Seems like the default behavior is now somehow overriding the extension.

**Comment by elliotwaite** [comment]
Ah, you're right. I'll look into this tomorrow. Thanks for reporting it.

**Comment by elliotwaite** [comment]
Just released a fix (version 1.3.6). It looks like YouTube recently changed the format of the default text in the tooltip. So I just had to update the code that parses that text.

Thanks again for opening this issue.

I'm going to close this issue, but if for some reason version 1.3.6 doesn't fix the issue for you, please let me know.
