### ISSUE TITLE
YouTube Data API v3 not available

### ISSUE THREAD

**Issue by guplem** [elliotwaite/thumbnail-rating-bar-for-youtube#43]
I followed the described steps to create the API Key, but I got stuck at the step "open the "Select APIs" dropdown menu and check the "YouTube Data API v3" checkbox."

[No such API exist](https://i.imgur.com/ZtomGXR.png) in the dropdown. Maybe they updated it or something, and it got removed, or I did something wrong.

Nevertheless, at the same time, I choose "Don't restrict key (This key can call any API)" and the extension doesn't work with the resulting key. So maybe I did something wrong before...

**Comment by guplem** [comment]
Never mind, apparently the enabling of the "YouTube Data API v3" didn't work or something. Redoing that step fixed it and the KPI became available.

GREAT EXTENSIONS!

**Comment by elliotwaite** [comment]
Glad you were able to get it working. Thanks for reporting this. I've added a note to that step of the instructions to help others that may run into this same issue.
