### ISSUE TITLE
video bar colors are reversed?

### ISSUE THREAD

**Issue by somefnfplayerlol** [elliotwaite/thumbnail-rating-bar-for-youtube#47]
is it just me or the colors on the video bar are reversed?
![image](https://user-images.githubusercontent.com/89298564/131774392-5e193722-03e8-40f1-92df-8285cf3172fa.png)

**Comment by elliotwaite** [comment]
You are correct. Oops. I'll fix this now.

**Comment by elliotwaite** [comment]
This issue should now be fixed in the latest release, version 1.4.4. Thanks for reporting this issue. I'm going to close this issue, but if the latest update doesn't resolve this issue for you, please let me know.
