### ISSUE TITLE
Like Percentage not shown when looking at the videos in a playlist

### ISSUE THREAD

**Issue by Qarthak** [elliotwaite/thumbnail-rating-bar-for-youtube#48]
![Image](https://user-images.githubusercontent.com/81775691/132254030-018b6dbc-4909-45d4-bc73-8a6339a112de.png)
It would be nice to be able to see the percentage for all videos in a playlist. 
On a lesser priority, another useful feature could would be statistics for the playlist like mean and variance for the ratio of likes over dislikes. This would provide a general idea about the playlist

**Comment by elliotwaite** [comment]
Good suggestions. I'll work on adding the rating text to each thumbnail soon. Adding rating info about the playlist as a whole would be harder and I'm not sure how much additional value that data would provide to users, so I probably won't work on adding that feature at the moment, but I'll leave the suggestion open as a potential addition in the future.

P.S. - Great playlist. Erik Demaine is the man. And the other professor is good too.

**Comment by elliotwaite** [comment]
Sorry for the delay. Something came up and I've been busy recently. But I just released the fix in version 1.4.5. Let me know if I should mark this issue as closed or if I should leave it open in regards to your feature request to add rating info about the playlist as a whole, such as the mean and variance of the ratings.

Also, thanks for opening this issue and requesting this fix.

![image](https://user-images.githubusercontent.com/1767836/133590572-4935737e-3724-4693-9f8b-4b63e844f630.png)

**Comment by Qarthak** [comment]
While having those stats would be somewhat useful, that is now what this issue is about, so I'm gonna close it. Thanks a lot for the update and the useful guide about the API key. It took me less than a minute to reinsert it as you already provided the link for where it would be in the future.

**Comment by elliotwaite** [comment]
Okay, sounds good.
