### ISSUE TITLE
Option to scale up the dislike bar as it's too small for most videos

### ISSUE THREAD

**Issue by Qarthak** [elliotwaite/thumbnail-rating-bar-for-youtube#49]
![Image](https://user-images.githubusercontent.com/81775691/132255209-f9e9f28b-884b-485f-8f00-1c5a846b1714.png)
As you can see these videos have too high a like/dislike percentage and it's hard to differentiate between a 1% long dislike bar vs a 0.1% dislike bar. It would be nice to have a feature that would let us scale up the number of dislikes by a constant factor for all videos so it's easier to tell which one has a better ratio

**Comment by Qarthak** [comment]
I tried to implement this in code but I'm not good at css or javascript or webdev in general. Also the variable names were converted to single characters too. If you can't implement the whole feature just guide me on where to add the *10 so that it works for me and anyone who comes across this later

**Comment by elliotwaite** [comment]
Interesting idea. Perhaps the option could say something like, "Logarithmicly scale the likes bar width to be able to better differentiate highly liked videos." And then the like bar width could be scaled by some logarithmic base that might correspond to something like:
* rating 100% = width 100%
* rating 90% = width 50%
* rating 80% = width 25%
* rating 70% = width 12.5%
* etc.

I'll try to implement something like this soon and let you know how it goes.

**Comment by elliotwaite** [comment]
I realized it would be called exponential scaling rather than logarithmic scaling. I just released a new version of the extension (1.4.6) that has a new option to enable exponential scaling:
![image](https://user-images.githubusercontent.com/1767836/133623285-50d32cbe-9b1d-4cf4-8eed-1caac0437119.png)

Let me know what you think and if you have any suggestions for how it could be improved.

**Comment by Qarthak** [comment]
It looks good. I just turned it on and I'm taking a while to get used to it. It's definitely better than linear scaling tho, although it would be nice to have an option to simply scale the dislike bar by a constant factor as exponentials are hard to decipher(twice as big doesn't mean twice the dislike ratio). I have no idea how scaling up would deal with the case where scaling factor*dislike percentage > 100% so ig exponential works

**Comment by elliotwaite** [comment]
Yeah, for the linear scaling, I thought it would be weird to just have a zero rating for ratings that were off the scale, and I wasn't sure of a different good way of handling it.

So far I've been liking the exponential scaling. I've been using it for the last 10 days and over that time I've gotten more familiar with which widths correspond with what types of ratings. A lot of updates that people request I never end up using, but this one I've actually found quite useful, so thanks again for the suggestion.

If you have any suggestions after trying it out for a bit, feel free to leave them here. Or if you think this update is good for now, you can close this issue, and if you have any other suggestions in the future, you can reopen this issue or create a new one.

**Comment by Qarthak** [comment]
This is pretty good. I think I'll also get used to the widths over time. It's also nice to have a more visual understanding of exponentials. I'll be closing this now, thanks for the updates man you rock! :D

**Comment by elliotwaite** [comment]
Thanks! Sounds good.
