### ISSUE TITLE
Feature Request - Score

### ISSUE THREAD

**Issue by Agarwal-Nikhil** [elliotwaite/thumbnail-rating-bar-for-youtube#5]
Hey, I tried this as the [other extension](https://chrome.google.com/webstore/detail/ratings-preview-for-youtu/cgbhdenfmgbagncdmgbholejjpmmiank) stopped working. I like your extension, just that the score is missing. The score is useful as it shows rating with respect to total no. of views.

**Comment by elliotwaite** [comment]
Thanks for the feature request. I am not sure yet if I am going to add a similar score function to this extension, but if there is enough interest I probably will. So far you are the second person who has mentioned to me that'd you'd like this feature added.

I never used the score feature with the other extension, but I saw that it would put the score as a percentage number in the bottom left of the thumbnail, which is also where the "WATCHED" tag goes after you've watched a video when you have your view history turned on. Do you know how the other extension dealt with this? Did it move the "WATCHED" tag to the top of the thumbnail, or hide it or something?

I was also thinking, maybe instead of a numerical score in the bottom left corner, maybe it could be a vertical bar on the left of the thumbnail, similar to the rating bar. What do you think about this idea?

**Comment by Agarwal-Nikhil** [comment]
Hi, I don't see the 'watched tag', even when I disable all my extensions. Even though the extensions that I mentioned is working now, I would still don't want to use it as it is closed source. But you could see how it works. The bar that your extension shows indicates the like to dislike ratio. I find the score useful as when the total no. of likes are less the score is lesser than the ratio. There is a certain threshold of likes beyond which the absolute number of likes don't matter but the ratio matters. 

For example the following video has low dislike to like ratio (about 3%), but the total no. of likes (about 100) is lower than the threshold so the Rating Score is less. 
![image](https://user-images.githubusercontent.com/18417820/42443932-1bf77b08-836f-11e8-84ec-7ff45ecd55f6.png)

But, the following video has lower dislike to like ratio (about 10%) but total no. of like (about 200) is closer to the threshold than the previous, so has higher Score.
![image](https://user-images.githubusercontent.com/18417820/42444163-add83508-836f-11e8-8c0d-cceb08df49d9.png)

**Comment by SwiftWinds** [comment]
Why was this issue closed? AFAIK, this issue has not yet been shipped. Could it be reopened? I am also interested in this feature

**Comment by SwiftWinds** [comment]
If it's helpful, I looked through the Ratings Preview for YouTube code, and I found the function that calculates the RP score:

```js
// Computes the total score of a video based on an intelligent algorithm
function totalScore(views, likes, dislikes) {
  var votes = likes + dislikes;

  if (votes > 0 && views > 0) {
    var likesScore =
      (likes / votes) *
        Math.min(
          log(
            Math.pow(10, 2),
            ((Math.pow(10, 2) - 1) * votes) / Math.pow(10, 3) + 1
          ),
          1
        ) +
      0.5 *
        (1 -
          Math.min(
            log(
              Math.pow(10, 2),
              ((Math.pow(10, 2) - 1) * votes) / Math.pow(10, 3) + 1
            ),
            1
          )); // [0, 1]

    var viewsScore = Math.min(
      log(
        Math.pow(10, 6),
        ((Math.pow(10, 6) - 1) * views) / Math.pow(10, 9) + 1
      ),
      1
    ); // [0, 1]

    var votesScore =
      1 -
      Math.min(
        log(
          Math.pow(10, 2 / 3),
          ((Math.pow(10, 2 / 3) - 1) * votes * 100) / views / Math.pow(10, 1) +
            1
        ),
        1
      ); // [0, 1]

    var totalRawScore = likesScore * 0.8 + viewsScore * 0.1 + votesScore * 0.1; // [0, 1]

    var totalNetScore = Math.min(Math.max(10.8 * totalRawScore - 0.4, 0), 10); // [-0.4, 10.4] truncated to [0, 10]

    return totalNetScore;
  } else {
    return 5;
  }
}
```

**Comment by elliotwaite** [comment]
I'm not sure why this issue was closed. I'll reopen it.

I currently only want to invest the time to maintain the current set of features, so I currently won't be working on adding this feature myself. But you are welcome to fork this repo and add that feature or submit a pull request.

**Comment by SwiftWinds** [comment]
Sure, I'll look into PRing this some time this week. :) Would adding the number in the video duration be fine or, do you think it'd best be a number in the bar itself or maybe something completely different?

**Comment by elliotwaite** [comment]
I think my first preference would be to display it on the bottom left of the thumbnail, on the opposite side of the duration. What do you think would look best?

**Comment by SwiftWinds** [comment]
I never even thought of that; I think that'd be a good use of thumbnail space. It sounds a bit harder but I'll try it out.

**Comment by anishmittal2020** [comment]
May be ratings can be assigned as mentioned here: 
- [How not to sort by average rating (2009)  - Hacker News](https://news.ycombinator.com/item?id=29200103)

**Comment by elliotwaite** [comment]
@anishmittal2020, thanks for the suggestion. A score like that could be interesting.
