### ISSUE TITLE
Older versions of the YouTube app still show dislikes

### ISSUE THREAD

**Issue by glibg10b** [elliotwaite/thumbnail-rating-bar-for-youtube#52]
Maybe this could be useful?

**Comment by elliotwaite** [comment]
@glibg10b, thanks for this idea. If this is still the case after Dec 13 (when they are removing dislikes from the API), I'll look into seeing if I can use the data from there instead.

**Comment by glibg10b** [comment]
@elliotwaite Turns out, it's YouTube Vanced that shows the dislikes, and from what I can tell, it relies on the API :(

**Comment by elliotwaite** [comment]
Okay, thanks for the update. I'll close this issue then. But feel free to reopen it or create a new one if you think of any other workarounds.
