### ISSUE TITLE
Return Youtube Dislike extension support

### ISSUE THREAD

**Issue by stoopingas** [elliotwaite/thumbnail-rating-bar-for-youtube#54]
A couple of weeks ago, a new open source browser extension was made that archives YouTube's like:dislike counts and applies user data to keep dislikes in use for those using the extension. If you have not heard about the extension yet, their official website is [https://returnyoutubedislike.com/](url)
I don't know how api, data, and coding actually works but if it is possible to use the like:dislike counts that this extension uses or possibly work in tandem with the extension then the thumbnail rating bar could continue to help its users. If this is not something that is possible then I apologize for wasting your time with this. Your extension meant a lot to me so thank you for making YouTube a better site to use over the past year. If this is it for Thumbnail Rating Bar then I will never forget this extension and the conveniences it brought to me. Thank you for everything.

**Comment by elliotwaite** [comment]
@stoopingas thanks for the suggestion and your support. There has been some discussion about collaborating with the creator of that extension here: https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/issues/50

My hope is that we'll be able to keep this extension going through 3rd party APIs.

**Comment by martin-braun** [comment]
I searched for it and I found this issue, thanks for being ahead of the issue. I'm glad this extension exists.

**Comment by banks2337** [comment]
would be amazing if you could collaborate with them and fix it. I hate to click on all the videos first to see the ratings.

Thanks so much for your work!

**Comment by elliotwaite** [comment]
An update to switch over the extension to use the Return YouTube Dislike API has been submitted to the Chrome Web Store for review. It should be available soon once it's approved. I'll post another comment here when it's available.

**Comment by elliotwaite** [comment]
The Chrome version is now available. After the update, you may need to approve the updated permissions to reenable the extension. The new permissions enable making API calls to `returnyoutubedislikeapi.com`.

I'm going to close this issue, but feel free to reopen it if the new API backend isn't working for you.
