### ISSUE TITLE
Rating previews recently stopped working.

### ISSUE THREAD

**Issue by ikingjosh** [elliotwaite/thumbnail-rating-bar-for-youtube#55]
Stopped working in the last day or two.  Just shows a full blue bar (100% rating) for every video.  Will there be a fix possible?

**Comment by jahanzebshayan** [comment]
youtube closed the dislike api so only possible fix would be to use [returnyoutubedislikeapi.com](https://github.com/Anarios/return-youtube-dislike/blob/main/Extensions/UserScript/Return%20Youtube%20Dislike.user.js#L265) to get the data

**Comment by ikingjosh** [comment]
But I've been using the Return Youtube Dislike chrome extension for over a week before the ratings preview extension stopped working.  
    On Tuesday, December 14, 2021, 03:28:37 PM CST, Jahanzeb Shayan Eqbal ***@***.***> wrote:  
 
 


youtube closed the dislike api so only possible fix would be to use returnyoutubedislikeapi.com to get the data

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by obviousaurus** [comment]
This isn't this developer's fault. Google changed the way that YouTube works and removed the Dislike counter. You can read up on this change here:

https://blog.youtube/news-and-events/update-to-youtube/

**Comment by piotr-kwiatkowski** [comment]
> This isn't this developer's fault. Google changed the way that YouTube works and removed the Dislike counter.

Yes, but that's not the answer to the question. The question is if it is possible to create a workaround and according to [this thread](https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/issues/54) the work is in progress.

**Comment by elliotwaite** [comment]
I just finished the update to fix this. The extension now uses the [Return YouTube Dislike](https://returnyoutubedislike.com) API instead of YouTube's. I submitted the update to the Chrome Web Store for review (version 1.6.0); they usually approve updates within a few hours. And the Firefox version is already released.

**Comment by elliotwaite** [comment]
Actually, the review might take longer this time. I got this message:
```Due to the Host Permission, your extension may require an in-depth review which will delay publishing.```

This is because I switched the URL being used for the API requests.

**Comment by ikingjosh** [comment]
Thanks the update Elliot!

**Comment by elliotwaite** [comment]
The Chrome version is now available. After the update, you may need to approve the updated permissions to reenable the extension. The new permissions enable making API calls to `returnyoutubedislikeapi.com`.

I'm going to close this issue, but feel free to reopen it if the new API backend isn't working for you.

**Comment by ikingjosh** [comment]
Working!  Thanks.  I manually updated the extension using these instructions
Start Google Chrome.
Click the vertical ellipsis icon. on the browser toolbar.
Select More Tools -> Extensions.
click the Developer Mode button on the right side of the header.
From there, you should see the “Update” button pop up on the upper left side
