### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by shivamkumarc** [elliotwaite/thumbnail-rating-bar-for-youtube#61]
Sir in Thumbnail Rating Bar for YouTube™ extension when we hover the mouse to thumbnail of the video, likes and dislikes on the video is the mere number only and not separated by a comma so I request GitHub  to fix this and put a comma on the number according to the international system of a comma between digits

**Comment by elliotwaite** [comment]
Thanks for the suggestion! Good idea. I just released an update (version 1.6.5) which implements this. If for some reason the update doesn't resolve this issue for you, let me know.

**Comment by shivamkumarc** [comment]
OMG, OMG, OMG, OMG, OMG I can`t believe you have fixed this issue, I can`t
believe you fixed the suggestion of simple men like me, thank you so much

**Comment by elliotwaite** [comment]
Haha, I'm glad to hear you like the update.

Thanks again for noticing this and taking the time to open an issue about it. I like getting these types of details right, and I'm sure others will appreciate your suggestion as well.

**Comment by shivamkumarc** [comment]
My pleasure!

**Comment by shivamkumarc** [comment]
Sir can you also fix the issue that like on the thumbnail rating bar is
updating late, it`s not a problem for old videos as like increment in the
old video is slow but when the recent video uploads like update really feel
slow, please match the like update with real-time

**Comment by elliotwaite** [comment]
@shivamkumarc, thanks for reporting this. I responded in the separate issue you opened about this: https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/issues/62
