### ISSUE TITLE
Issue Fix

### ISSUE THREAD

**Issue by shivamkumarc** [elliotwaite/thumbnail-rating-bar-for-youtube#62]
Sir can you also fix the issue that like on the thumbnail rating bar is updating late, it`s not a problem for old videos as like increment in the old video is slow but when the recent video uploads, like update really feel slow, please match the like update with real-time

**Comment by elliotwaite** [comment]
I think this is an issue with the Return YouTube Dislike API that this extension uses. It seems to be a little slow to update with new likes/dislikes data. I'm not sure if there is much I can do about this.

**Comment by shivamkumarc** [comment]
Can you keep collecting youtube dislike data from return youtube dislike
extension as there is no option but you can update youtube likes in
real-time because youtube itself shows it

**Comment by elliotwaite** [comment]
This is an interesting idea. Currently, using only the Return YouTube Dislike API simplifies things a lot, so I'm not sure I'd want to take on the development effort to implement this feature. But if someone would want to work on implementing this, I would be open to reviewing any pull requests for it.

**Comment by shivamkumarc** [comment]
Ok, once your team expand then apply this feature, thanks for now

**Comment by shivamkumarc** [comment]
I find one bug in the extension that when you see the rating bar in the
video, it shows the correct number of likes on the video but when you see
the same video on playlist list same video TRB extension, shows more number
of likes than that video actually has, I mean suppose in reality that video
has 17.3k likes but when you see the rating bar when in the playlist it
shows 18.4k like, please can you fix this issue

**Comment by elliotwaite** [comment]
I have seen that most videos are off by 1, but haven't been able to find any videos off by 1k yet. Can you link me to a video where you've noticed this issue?

**Comment by shivamkumarc** [comment]
Sir now this problem is fixed for all playlists but for this playlist
topmost video it shows more number of likes else it`s fixed now
https://www.youtube.com/playlist?list=PLU6SqdYcYsfIgl58LabHfHW3mksEWimFs

**Comment by shivamkumarc** [comment]
Yes sir in almost every case it shows more number of likes under 1k only

**Comment by shivamkumarc** [comment]
But for a few playlists, it differs by more than 1k also e.g.3rd video of
this playlist
https://www.youtube.com/playlist?list=PL9bw4S5ePsEEqCMJSiYZ-KTtEjzVy0YvK

**Comment by elliotwaite** [comment]
Ah, I see. Thanks for pointing these out. It seems like this is an issue with the Return YouTube Dislike API. Perhaps the API data will improve with time and its data will be more up to date. If it doesn't ever improve, maybe this extension could add the option to use both the Return YouTube Dislike API along with the YouTube API. It could get the predicted likes/dislikes from Return YouTube Dislike API, and then get the actual likes from the YouTube API, and scale the predicted dislikes by [actual likes / predicted likes]. But I'm hoping this is just a scaling issue for Return YouTube Dislike. They have posted stats in their Discord channel about how fast their traffic is growing, so it might just take a bit for them to figure out the best way to collect and manage all that data.

**Comment by shivamkumarc** [comment]
Thanks for the reply,hope API data will improve soon

**Comment by shivamkumarc** [comment]
Sir what is this rating cache duration

**Comment by shivamkumarc** [comment]
Hello sir can you reply to me please, what is the rating cache duration

**Comment by elliotwaite** [comment]
> Sir what is this rating cache duration

Good question. Some others are probably also wondering the same thing, so I added a section about the cache to the README: https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube#rate-limiting-and-the-cache-duration-setting

Also, in the latest update (version 1.7.2), I added a link to this explanation to the options page. Thanks for the question.

**Comment by shivamkumarc** [comment]
Thanks

**Comment by elliotwaite** [comment]
Is it okay if I close this issue, or should I leave it open?

**Comment by shivamkumarc** [comment]
Yes sir you can close the issue.

**Comment by elliotwaite** [comment]
Okay.
