### ISSUE TITLE
New Extension

### ISSUE THREAD

**Issue by shivamkumarc** [elliotwaite/thumbnail-rating-bar-for-youtube#65]
Can you make a new extension whose work be only to show no of likes and no of dislikes on every youtube video below the title of the video, actually for me Elliot Waite sir had created locally but a new extension will be nice

**Comment by elliotwaite** [comment]
Thanks for the suggestion. I currently don't want to invest the time to work on this. But I'll leave this recommendation open and perhaps I'll get to it eventually.

For anyone else who is interested in this feature and also wants to implement it in a local copy of the extension, you can try to follow the instructions that I gave to @shivamkumarc here: https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/issues/64

**Comment by shivamkumarc** [comment]
Thanks when you get time then you can create the new extension

**Comment by elliotwaite** [comment]
I'm going to close this issue since it is similar to https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/issues/64. I think it would be better for organizational reasons to keep all discussions about this feature in one thread.
