### ISSUE TITLE
Change in extension

### ISSUE THREAD

**Issue by shivamkumarc** [elliotwaite/thumbnail-rating-bar-for-youtube#66]
Guys, I want your all opinion on replacing like percentage with number of likes and dislike below the title of the video so the developer of the extension can do this or maybe when we hover to rating bar that can be replaced by like percentage with number of likes and dislike

**Comment by elliotwaite** [comment]
I'm going to close this issue since it is similar to https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/issues/64. I think it would be better to keep all discussions about this issue in one place.
