### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by shivamkumarc** [elliotwaite/thumbnail-rating-bar-for-youtube#67]
Can you replace the like percentage with the number of likes and dislike below the title of the video as the number of likes and dislike data is more necessary than the like percentage

**Comment by elliotwaite** [comment]
I like to keep issues consolidated, so I'm going to close this issue. Please keep posts about this topic in this issue: https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/issues/64
