### ISSUE TITLE
Extension Code

### ISSUE THREAD

**Issue by shivamkumarc** [elliotwaite/thumbnail-rating-bar-for-youtube#68]
Sir where we will find latest code of extension ?
Is it where i shown in picture sir where we will get latest code by downloading zip.
![Screenshot (217)](https://user-images.githubusercontent.com/96905752/151704277-ff473a0f-88c9-477c-ae91-52c1b46ee462.png)

**Comment by elliotwaite** [comment]
Yep, that will download the latest code.

I'm going to close this issue, but feel free to open a new issue or leave any more comments here if you have any other questions.
