### ISSUE TITLE
Extension doesn't work anymore - voting values too low / wrong (Chrome)

### ISSUE THREAD

**Issue by WurstCommander** [elliotwaite/thumbnail-rating-bar-for-youtube#71]
Hi,

I think the extension doesn't work anymore, maybe only on Chrome.
For new videos, the values for likes / dislikes are unrealistic low / wrong and it doesn't show the same values the "Return Youtube Dislike" - Extension shows.

I really like this add-on and I hope it can be fixed.

![image](https://user-images.githubusercontent.com/5268576/161837941-7279345a-8e0d-4486-85e9-34d35f62aecd.png)

vs
![image](https://user-images.githubusercontent.com/5268576/161838005-cb90af29-1c72-4fde-8075-027dcf8adeab.png)

**Comment by elliotwaite** [comment]
Okay, thanks for reporting this. I'll look into it.

**Comment by elliotwaite** [comment]
Looks like Return YouTube Dislike was experiencing technical difficulties yesterday (https://github.com/Anarios/return-youtube-dislike/issues/523), but they said it should be fixed now. Hopefully things will return to normal soon. If they don't, let me know.

**Comment by PickleNik** [comment]
<img width="607" alt="Screen Shot 2022-04-05 at 9 35 30 PM" src="https://user-images.githubusercontent.com/31113245/161878022-3e15e64d-5556-4ea4-951c-5022156c2b50.png">

**Comment by PickleNik** [comment]
@elliotwaite should be good now, you can close this :)

**Comment by elliotwaite** [comment]
@PickleNik okay, thanks for the update.
