### ISSUE TITLE
Does it matter I use "Return YT Dislikes" userscript (tampermonkey)

### ISSUE THREAD

**Issue by redrios** [elliotwaite/thumbnail-rating-bar-for-youtube#74]
I'm functional code illiterate, so wanna ask if its the same (same synergy/linkage) if I use both  this extension and the "Return [...]" one on my chromium browser or both this extension and the "Return" script for tampermonkey on my chromium browser--
I know it has to do with APIS and reading of them by one, but idk if its relevant to how they're there..,. I'm talkin about the functionality specifically where you peak  on condition of using both extensions in parenthesis in the main GitHub page in this repository

**Comment by elliotwaite** [comment]
Installing the "Return YouTube Dislike" extension is optional, and if you do install it, it won't make a difference whether you install it as a Chromium extension or through tampermonkey.

In regards to this part of the README:
> If you would also like to see the likes/dislikes rating bar that used to be available on each video page, you can also install [their extension](https://returnyoutubedislike.com/install).

That just means that the "Return YouTube Dislike" extension adds that feature on its own independent of this extension.

And in regard to this part of the README:
> Note: If you also have the [Return YouTube Dislike extension](https://returnyoutubedislike.com/install) installed, which adds a rating bar to the video page, this option will affect the scaling of that rating bar as well.

That just means that if the "Return YouTube Dislike" extension has added the rating bar to the video page, this extension will scale that rating bar according to the settings in this extension. But the rating bar is detected just by reading the HTML on that page, so it won't matter how that HTML was added, meaning it won't matter whether the "Return YouTube Dislike" extension that was installed through Chromium or tampermonkey.

Let me know if this sufficiently answers your question.

**Comment by redrios** [comment]
ty so much for the clear response! now its clear

**Comment by elliotwaite** [comment]
Nice, I'm glad you like it.
