### ISSUE TITLE
No more Working

### ISSUE THREAD

**Issue by shivamkumarc** [elliotwaite/thumbnail-rating-bar-for-youtube#75]
Please fix this extension as this extension is no more working,now it`s not loading likes and dislike data or thumbnail rating bar

**Comment by shivamkumarc** [comment]
Now finally working 😊😊😊

**Comment by elliotwaite** [comment]
Okay, thanks for reporting the issue. I'm not sure why the extension wasn't working for a bit, but perhaps the Return YouTube Dislike API was having technical issues.

**Comment by shivamkumarc** [comment]
Yes it was return youtube dislike extension having  problem for some time
![Screenshot (501)](https://user-images.githubusercontent.com/96905752/181082201-1aff145c-a834-4cf1-b691-56f3d320f997.png)

**Comment by elliotwaite** [comment]
Okay, good to know.
