### ISSUE TITLE
[Bug] (LibreWolf) Rating bar on video page doesn't scale correctly with exponential scaling on

### ISSUE THREAD

**Issue by RenegadeScooter** [elliotwaite/thumbnail-rating-bar-for-youtube#77]
![Screenshot 2022-09-26 213324](https://user-images.githubusercontent.com/69838290/192432835-bc72ed1d-97cf-4aa6-a66e-49c39ce4a41a.jpg) Exponential scaling should make this video page rating bar half-green and half-red because the video has 90% likes, but instead all except one pixel is red. I am using **LibreWolf version 105.0.1-1**, based on the same version of Firefox. I took the screenshot at 75% zoom.

**Comment by RenegadeScooter** [comment]
![Screenshot 2022-09-26 220554](https://user-images.githubusercontent.com/69838290/192436698-66c8137e-e1a4-4829-8985-85dc008c91db.jpg) In _this_ case, the bar is completely red despite the video having 99.6% likes.

**Comment by elliotwaite** [comment]
@RenegadeScooter, thanks for reporting this issue. I noticed that the thumb icons are green and red. Do you have a custom YouTube theme or something like that installed through some other extension? If so, that extension and this one may be interfering with each other in how they are trying to update that rating bar.

**Comment by RenegadeScooter** [comment]
![Screenshot 2022-09-27 005623](https://user-images.githubusercontent.com/69838290/192467684-b9e8daab-88c6-4823-b69b-1433b322dee6.jpg) The only YouTube-related extensions I have are SponsorBlock, Return YouTube Dislike, Thumbnail Rating Bar, Enhancer for YouTube and vidIQ Vision. Return YouTube Dislike and Thumbnail Rating Bar are the only ones that control the rating bar. I have Enhancer for YouTube enforcing the official dark theme, and disabling that setting doesn't solve the issue.
Here are my settings for Return YouTube Dislike and Thumbnail Rating Bar, if it helps:
![Screenshot 2022-09-27 005141](https://user-images.githubusercontent.com/69838290/192466692-68cddd17-7b55-484f-8399-e3a4cfac2818.jpg) ![Screenshot 2022-09-27 005318](https://user-images.githubusercontent.com/69838290/192467046-84e5e057-e736-4522-bbfb-1657e4ea8d89.jpg)

**Comment by elliotwaite** [comment]
Thanks, I'm able to reproduce the issue with those Return YouTube Dislike settings. I'll work on a solution and let you know when I have an update.

**Comment by elliotwaite** [comment]
I just released a fix (version 1.8.6). You should be able to update the extension from the Extensions page, although I'm not familiar with LibreWolf. When you get the chance, feel free to try it out and let me know if it resolves the issue for you.
