### ISSUE TITLE
Does not save options on Firefox 106

### ISSUE THREAD

**Issue by sttffe** [elliotwaite/thumbnail-rating-bar-for-youtube#79]
Does not save options (colors, states of check-boxes) on Firefox 106.0 (Windows 10, 64-bit).

**Comment by elliotwaite** [comment]
@sttffe thanks for reporting this. I don't have access to a Windows device right now, but I might be able to test it on one later today. For now, I just tested it on Firefox 106.0 on a Mac and it seems to be working correctly.

A couple of questions:
1. Are you making sure to click the blue "Save" button in the bottom right corner of the extension after changing your settings? (The settings don't auto-save when you change them. Maybe this should be updated in the future.)
2. After you save your settings, are they lost even when just closing and reopening the settings menu, or do you have to close and reopen Firefox for the settings to be lost?

**Comment by sttffe** [comment]
1. _Are you making sure to click the blue "Save" button ...?_
Yes, I do click the blue "Save" button, and then it appears a popup saying "Settings saved. Refresh the page". After refreshing the page new settings are not applied.

2. _After you save your settings, are they lost ...?_
New settings are lost when just closing and reopening the settings menu (no reopening Firefox).

**Comment by elliotwaite** [comment]
Sorry for the delay in reply. I just tested using the extension on Windows with the latest Firefox version and I was able to save changes to the settings. Since I'm unable to replicate this issue, I'm not sure how to debug it.

Are you still unable to save any changes?

**Comment by sttffe** [comment]
In Firefox 107 I still have the reported problem

I tried some debugging and get the following

![image](https://user-images.githubusercontent.com/66207199/202674119-6027b12f-0ba6-4304-86d0-c4952c4f1716.png)

**Comment by elliotwaite** [comment]
Thanks, this info help. I'll look into it more soon and let you know what I find.

**Comment by elliotwaite** [comment]
I just released an update ([version 1.8.7](https://addons.mozilla.org/en-US/firefox/addon/youtube-thumbnail-rating-bar/versions/)) that I think will resolve this issue. I switched from using sync storage to local storage. Can you test it out when you get a chance and let me know if this fixes the issue for you?

**Comment by sttffe** [comment]
The problem disappeared. Works as expected.
Thank you very much for the extension.

**Comment by elliotwaite** [comment]
Nice. I'm glad to hear it's fixed. Thanks again for reporting this issue, and feel free to open any other issues if you notice anything else not working as expected in the future.
