### ISSUE TITLE
Roll Back Previous Version

### ISSUE THREAD

**Issue by shivamkumarc** [elliotwaite/thumbnail-rating-bar-for-youtube#88]
I would recommend you remove thumbnail rating support for YouTube shorts as it takes a considerable amount of time to load Thumbnail ratings for YouTube videos and ruins User Experience

**Comment by elliotwaite** [comment]
Okay, I've disabled adding rating bars to shorts in the latest update (version 1.8.16). Maybe in the future, this could be made an option in the settings.

**Comment by shivamkumarc** [comment]
Thanks
