### ISSUE TITLE
Extension Issue

### ISSUE THREAD

**Issue by shivamkumarc** [elliotwaite/thumbnail-rating-bar-for-youtube#89]
The extension is not working, Please fix it

**Comment by elliotwaite** [comment]
I think the Return YouTube Dislike server might be down. Their API is returning `502 Bad Gateway` errors.

Also, this issue was recently posted in their repo: https://github.com/Anarios/return-youtube-dislike/issues/1029

**Comment by shivamkumarc** [comment]
Hope Return YouTube Dislike gets fixed soon

**Comment by shivamkumarc** [comment]
Is there an alternate way for Return Youtube Dislike, that you can fix the extension? or do we`ve to wait for RYD to be fixed?

**Comment by elliotwaite** [comment]
There isn't a simple alternative solution that I know of, other than just waiting for them to fix the issue. But they usually fix these types of issues within a few days.

**Comment by elliotwaite** [comment]
I'm going to close this issue since it is working again now, but thanks for reporting this.
