### ISSUE TITLE
Chrome Webstore link broken

### ISSUE THREAD

**Issue by fatneko** [elliotwaite/thumbnail-rating-bar-for-youtube#9]
I'm getting a "Error 404" when clicking on the Chrome Webstore link, was the extension removed?

Link:
https://chrome.google.com/webstore/detail/youtube-thumbnail-rating/cmlddjbnoehmihdmfhaacemlpgfbpoeb

**Comment by elliotwaite** [comment]
Yeah, it was taken down due to branding guideline violations. I had to move the "YouTube" part of the title to the end and make it "for YouTube." I also had to change the icon to not use the exact YouTube icon. I have made the changes they requested, but they are taking a while to get back to me with an update. Hopefully, it'll be back up soon.

**Comment by alexchandel** [comment]
Any updates on this? Could you try resubmitting it?

**Comment by elliotwaite** [comment]
I just updated the extension again and resubmitted it, replacing the logo with an even more generic thumb icon, in case the previously updated icon was still in violation of their branding guidelines for some reason. I also sent them another email, the fourth one in a row with no reply yet.

**Comment by gotgoo** [comment]
Hi, in the meantime is it possible to make a userscript version and upload that? Since it doesnt seem that Google is going to reply... Although i'm not quite sure how much extra work that actually takes, so i apologize if that would be an unreasonable request.

**Comment by elliotwaite** [comment]
@gotgoo, I haven't researched creating userscripts, but all the code is open source if you or anyone else wants to convert this extension into a userscript.

**Comment by elliotwaite** [comment]
Also, an update on the Chrome Web Store takedown. They contacted me on Jan 18th with some additional changes that I had to make, and I made those changes and resubmitted it. So some progress, but still waiting to hear back from them again, and last time it took them 3 months to reply, so not sure how long it will take this time.

**Comment by ishanray** [comment]
can you link to the crx file directly please. that way we can still install it manually.

**Comment by elliotwaite** [comment]
@ishanray, good idea. It looks like Chrome no longer allows installing CRX files directly, so I just created a zip of the extension. I've added instructions to the README on how to download the zip file and install this extension manually: https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube

Thanks for the suggestion.

**Comment by elliotwaite** [comment]
The Chrome Webstore link is working again. They finally approved the update.
https://chrome.google.com/webstore/detail/thumbnail-rating-bar-for/cmlddjbnoehmihdmfhaacemlpgfbpoeb
