### ISSUE TITLE
SRS Document

### ISSUE THREAD

**Issue by shivamkumarc** [elliotwaite/thumbnail-rating-bar-for-youtube#90]
Can you Please provide us SRS Document for this Project?

**Comment by shivamkumarc** [comment]
We want to work on this for our Collge Project !!

**Comment by elliotwaite** [comment]
@shivamkumarc, I'm not sure what you would want in the SRS. Can you explain?

Also, I don't have much time right now to invest in working on this extension, but you are welcome to fork it and improve upon it as much as you want. Or if you had some small PRs you wanted to merge, I review them when I find some time.

**Comment by shivamkumarc** [comment]
No just our Teacher said to do work on any Project we should have SRS Documentation for that Project then only we`re allowed to take that Project and do Enhancement on that

**Comment by elliotwaite** [comment]
Ah, go it. Yeah, with my limited availability, maybe another project would be better to work on for now, but thanks for offering to help.

**Comment by shivamkumarc** [comment]
I am just curious to know if you`ve Created this project alone or as a Team?

**Comment by elliotwaite** [comment]
I created this project mostly alone, but also got help from the GitHub community, through PRs and helpful suggestions.
