### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by shhivaam** [elliotwaite/thumbnail-rating-bar-for-youtube#92]
It`s not Working,Please look into it

**Comment by elliotwaite** [comment]
It looks like it's an issue with the Return Youtube Dislike API: https://github.com/Anarios/return-youtube-dislike/issues/1093#issuecomment-2400752121

Hopefully they will resolve the issue soon.

**Comment by elliotwaite** [comment]
It looks like the extension is working again, so I'm going to close this issue, but thanks for reporting this.
